
spring:
  application:
    name: mofid.code.challenge
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

---
spring:
  config:
    activate:
      on-profile: postgres
  autoconfigure:
    exclude: []
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/balance}
    username: ${DB_USERNAME:balance}
    password: ${DB_PASSWORD:balance}
  flyway:
    enabled: true